// src/disposition/types.ts
/**
 * E05 disposition-gate contracts. The gate reads ONLY this structured rollup
 * (Joshua-curated, generated by ~/.claude/scripts/disposition-rollup.js) — never
 * the free-text decision-signal memories (D-E05-2). Read-only (D-E05-6).
 */

export type DispositionBucket =
  | 'thin' | 'override-prone' | 'high-trust' | 'modify-prone' | 'mixed';

/** The four autonomy actions the gate maps each bucket to (D-E05-1). */
export type GateAction = 'proceed' | 'proceed-supervised' | 'escalate' | 'hold';

export interface DispositionEntry {
  // accept / modify / override / defer counts; n = total signals (n<2 ⇒ thin).
  a: number; m: number; o: number; d: number; n: number;
  bucket: DispositionBucket;
}

export interface DispositionRollup {
  generatedFrom: number;
  domains: Record<string, DispositionEntry>;
  topics: Record<string, DispositionEntry>;
}

export interface GateVerdict {
  action: GateAction;
  bucket: DispositionBucket;
  matchedTopic: string | null; // exact topic, falling-back domain, or null
  reason: string;
}
